name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
    name: Build the Docker image
        uses: actions/checkout@v2
        run: docker build . --file Dockerfile --tag coesnakeyaml:2.0.0-$(date +%s)
    -
    name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: coe/snakeyaml:latest
    